name: software-carpentries-scikit-hep-tutorial
channels:
  - conda-forge
dependencies:
  - scikit-hep==3.6.0
  - scikit-hep-testdata==0.4.15
  - lz4==3.1.10
  - matplotlib==3.5.1
  - numba==0.55.2
  - numpy==1.21.5
  - pandas==1.4.3
  - python=3.9
  - python-xxhash==3.0.0
  - xrootd==5.4.3
  - zstandard==0.18.0
  - pip==22.2.1
  - nlopt==2.7.1   # https://github.com/zfit/zfit/issues/387
  - pip:
      - fastjet==3.3.4.0rc9
      - zfit==0.9.0a3 # Only remaining blocker for 3.10
